// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.DNSSECChecker
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("domain")]
        public string Domain { get; set; }

        [JsonProperty("dnssecEnabled")]
        public bool DnssecEnabled { get; set; }

        [JsonProperty("valid")]
        public bool Valid { get; set; }

        [JsonProperty("records")]
        public Records Records { get; set; }

        [JsonProperty("errors")]
        public object[] Errors { get; set; }

        [JsonProperty("details")]
        public Details Details { get; set; }

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("recommendation")]
        public string Recommendation { get; set; }
    }

    public partial class Details
    {
        [JsonProperty("dnskeyCount")]
        public long DnskeyCount { get; set; }

        [JsonProperty("dsCount")]
        public long DsCount { get; set; }
    }

    public partial class Records
    {
        [JsonProperty("dnskey")]
        public long Dnskey { get; set; }

        [JsonProperty("ds")]
        public long Ds { get; set; }

        [JsonProperty("nsec")]
        public string Nsec { get; set; }
    }
}
